### PR TITLE
Fix bad english

### PR DESCRIPTION
**Pull request by Mstrodl**
🇧🇷

### CODE REVIEW

**Comment by slice** [comment]
HEC KOFF BINCH MY PR OIS BETTER!!!!

**Comment by Mstrodl** [comment]
MINE IS NEWER :b:INCH

**Comment by Mstrodl** [comment]
I MEAN MINE CAME FIRST

**Comment by slice** [comment]
lol i won

**Comment by Mstrodl** [comment]
harassed online

**Comment by Mstrodl** [comment]
Stop bullying me pls

**Comment by slice** [comment]
[REAL] [911 CALLED] [NOT CLICKBAIT] [ARRESTED]

**Comment by Mstrodl** [comment]
@slice pls reply

**Comment by slice** [comment]
i did dumb binch

**Comment by Mstrodl** [comment]
REPLY AGAIN

**Pull request closed without merging**
